api_platform:
  mapping:
    paths: ['%kernel.project_dir%/src/Entity']
  patch_formats:
    json: ['application/merge-patch+json']
  swagger:
    versions: [3]
    api_keys:
      API_KEY:
        name: Authorization
        type: header

  # The title of the API.
  title: 'CSE Platform'

  # The description of the API.
  description: |
    ''

  # Enable Swagger ui.
  enable_swagger_ui: false

  # Enable ReDoc.
  enable_re_doc: false

  # Enable the entrypoint.
  enable_entrypoint: false

  # Enable the docs.
  enable_docs: true

  # Enable the data collector and the WebProfilerBundle integration.
  enable_profiler: true

  defaults:
    stateless: true
    # Good cache defaults
    cache_headers:
      vary:
        [
          'Content-Type',
          'Authorization',
          'Origin',
        ]

    collection:
      # The default order of results.
      order: 'ASC'

      pagination:
        # To enable or disable pagination for all resource collections by default.
        enabled: true

        # The default number of items per page.
        items_per_page: 2

        # To allow the client to enable or disable the pagination.
        client_enabled: true

        # To allow the client to set the number of items per page.
        client_items_per_page: true

        # The default name of the parameter handling the page number.
        page_parameter_name: 'page'

        # The name of the query parameter to set the number of items per page.
        items_per_page_parameter_name: 'count'
