version: '3.5'

services:

    nginx:
      image: ${COMPOSE_PROJECT_NAME}_nginx:latest
      build:
        context: ./docker/
        args:
          BUILD_ARGUMENT_ENV: dev
        dockerfile: ./nginx/Dockerfile
      container_name: ${COMPOSE_PROJECT_NAME}_nginx
      restart: always
      ports:
        - "${NGINX_PORT}:80"
        - "${NGINX_SSL_PORT}:443"
      volumes:
        - .:/var/www/html:ro,cached
      depends_on:
        - symfony
      networks:
        - cse_platform

    symfony: &symfony-template
      image: ${COMPOSE_PROJECT_NAME}_symfony:latest
      build:
        context: .
        args:
          BUILD_ARGUMENT_ENV: dev
          HOST_UID: ${HOST_UID}
          HOST_GID: ${HOST_GID}
        dockerfile: ./Dockerfile
      container_name: ${COMPOSE_PROJECT_NAME}_symfony
      volumes:
        - .:/var/www/html:cached
      depends_on:
        - db
      networks:
        - cse_platform

    db:
      image: mariadb:latest
      container_name: ${COMPOSE_PROJECT_NAME}_mysql
      command: --default-authentication-plugin=mysql_native_password
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: cseplatform
        MYSQL_USER: cseplatform
        MYSQL_PASSWORD: password
        MYSQL_HOST: db
      ports:
        - "3306:3306"
      volumes:
        - db_data:/var/lib/mysql:delegated
        - ./docker/dev/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
      networks:
        - cse_platform

    adminer:
      image: adminer:latest
      container_name: ${COMPOSE_PROJECT_NAME}_adminer
      ports:
        - "8080:8080"
      depends_on:
        - db
      networks:
        - cse_platform

networks:
  cse_platform:
    name: cse_platform
    external: true

volumes:
  db_data: ~
