<?php

namespace ContainerTpQLtNW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_AqMZmqyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.AqMZmqy' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.AqMZmqy'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\CheckHealthController::checkUpAction' => ['privates', '.service_locator.aws8lJM', 'get_ServiceLocator_Aws8lJMService', true],
            'App\\Controller\\CreateRentalController::__invoke' => ['privates', '.service_locator.h4gMbBE', 'get_ServiceLocator_H4gMbBEService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'App\\Controller\\CheckHealthController:checkUpAction' => ['privates', '.service_locator.aws8lJM', 'get_ServiceLocator_Aws8lJMService', true],
            'App\\Controller\\CreateRentalController:__invoke' => ['privates', '.service_locator.h4gMbBE', 'get_ServiceLocator_H4gMbBEService', true],
            'App\\Controller\\CreateRentalController' => ['privates', '.service_locator.h4gMbBE', 'get_ServiceLocator_H4gMbBEService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
        ], [
            'App\\Controller\\CheckHealthController::checkUpAction' => '?',
            'App\\Controller\\CreateRentalController::__invoke' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\CheckHealthController:checkUpAction' => '?',
            'App\\Controller\\CreateRentalController:__invoke' => '?',
            'App\\Controller\\CreateRentalController' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
