<?php

namespace ContainerTpQLtNW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCreateRentalControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\CreateRentalController' shared autowired service.
     *
     * @return \App\Controller\CreateRentalController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/CreateRentalController.php';
        include_once \dirname(__DIR__, 4).'/src/Service/RentalService.php';

        $container->services['App\\Controller\\CreateRentalController'] = $instance = new \App\Controller\CreateRentalController(new \App\Service\RentalService(($container->privates['App\\Repository\\RentalRepository'] ?? $container->load('getRentalRepositoryService'))));

        $instance->setContainer(($container->privates['.service_locator.W9y3dzm'] ?? $container->load('get_ServiceLocator_W9y3dzmService'))->withContext('App\\Controller\\CreateRentalController', $container));

        return $instance;
    }
}
