<?php

namespace ContainerTpQLtNW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserProviderService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Knp\DoctrineBehaviors\Provider\UserProvider' shared autowired service.
     *
     * @return \Knp\DoctrineBehaviors\Provider\UserProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/knplabs/doctrine-behaviors/src/Contract/Provider/UserProviderInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/knplabs/doctrine-behaviors/src/Provider/UserProvider.php';

        return $container->services['Knp\\DoctrineBehaviors\\Provider\\UserProvider'] = new \Knp\DoctrineBehaviors\Provider\UserProvider(($container->privates['security.helper'] ?? $container->load('getSecurity_HelperService')), NULL);
    }
}
