<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFeAFC6b\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFeAFC6b/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFeAFC6b.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFeAFC6b\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFeAFC6b\App_KernelDevDebugContainer([
    'container.build_hash' => 'FeAFC6b',
    'container.build_id' => '5705f051',
    'container.build_time' => 1655737486,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFeAFC6b');
