<?php

namespace ContainerFeAFC6b;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCreateImageControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\CreateImageController' shared autowired service.
     *
     * @return \App\Controller\CreateImageController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Controller/CreateImageController.php';
        include_once \dirname(__DIR__, 4).'/src/Service/ImageService.php';

        return $container->services['App\\Controller\\CreateImageController'] = new \App\Controller\CreateImageController(new \App\Service\ImageService(($container->privates['App\\Repository\\ItemRepository'] ?? $container->load('getItemRepositoryService'))));
    }
}
