<?php

namespace ContainerFeAFC6b;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getItemDataProviderService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\DataProvider\ItemDataProvider' shared autowired service.
     *
     * @return \App\DataProvider\ItemDataProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/core/src/DataProvider/RestrictedDataProviderInterface.php';
        include_once \dirname(__DIR__, 4).'/src/DataProvider/ItemDataProvider.php';

        return $container->privates['App\\DataProvider\\ItemDataProvider'] = new \App\DataProvider\ItemDataProvider(($container->privates['App\\Repository\\ItemRepository'] ?? $container->load('getItemRepositoryService')), ($container->privates['security.helper'] ?? $container->load('getSecurity_HelperService')));
    }
}
