<?php

namespace ContainerFeAFC6b;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRentalService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.h4gMbBE.App\Entity\Rental' shared service.
     *
     * @return \App\Entity\Rental
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.h4gMbBE": it references class "App\\Entity\\Rental" but no such service exists.');
    }
}
